-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
    FROM REST_INFO i1
    WHERE FAVORITES = (
        SELECT max(FAVORITES)
            FROM REST_INFO i2
            WHERE i1.FOOD_TYPE=i2.FOOD_TYPE
    )
    ORDER BY FOOD_TYPE DESC
;