SELECT CAR_ID, 
    CASE WHEN (MAX(START_DATE <= '20221016' AND END_DATE >= '20221016')) THEN '대여중'
    ELSE '대여 가능'
    END
    as AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
;