-- 코드를 입력하세요
SELECT distinct c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c, CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE MONTH(h.START_DATE) = 10
AND c.CAR_TYPE = '세단'
AND h.CAR_ID = c.CAR_ID
ORDER BY c.CAR_ID DESC
;