SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM FISH_INFO i, FISH_NAME_INFO n
WHERE i.FISH_TYPE = n.FISH_TYPE
AND i.LENGTH = (
    SELECT MAX(i2.LENGTH)
    FROM FISH_INFO i2
    WHERE i.FISH_TYPE = i2.FISH_TYPE
)
ORDER BY i.ID;