SELECT i.id as id, n.FISH_NAME as FISH_NAME, i.LENGTH as LENGTH
FROM FISH_INFO i, FISH_NAME_INFO n
WHERE i.FISH_TYPE = n.FISH_TYPE
AND i.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO i2
    WHERE i2.FISH_TYPE = i.FISH_TYPE
)
ORDER BY i.id;