SELECT b.CATEGORY as CATEGORY, SUM(s.SALES) as TOTAL_SALES
FROM BOOK b LEFT JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
AND YEAR(s.SALES_DATE) = 2022 
AND MONTH(s.SALES_DATE) = 1
GROUP BY b.CATEGORY
ORDER BY CATEGORY
;